name: Push Workflow

on:
  workflow_run:
  workflows:[First Workflow]
  types:
   - completed

jobs:
  push-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run on push
        run: echo "Code was pushed to main!"